using System;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;
using System.Security;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: ComVisibleAttribute(false)]
[assembly: CLSCompliantAttribute(false)]
[assembly: AssemblyCompanyAttribute("Solyutor")]
[assembly: AssemblyVersionAttribute("1.0.0.1")]
[assembly: AssemblyFileVersionAttribute("1.0.0.1")]
[assembly: AssemblyInformationalVersionAttribute("1.0.0.cd6710b1230c8992b2e91bce3f9eabd8aaadfef0")]
[assembly: AssemblyTitleAttribute("Solyutor.EventPublisher")]
[assembly: AssemblyProductAttribute("Solyutor.EventPublisher")]
[assembly: AssemblyDescriptionAttribute("Solyutor.EventPublisher is a product of Solyutor - ..")]
[assembly: AssemblyTrademarkAttribute("Solyutor.EventPublisher - Solyutor")]
[assembly: AssemblyCopyrightAttribute("Copyright ©  2011 Solyutor, - Original author or authors")]

