using System;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;
using System.Security;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: ComVisibleAttribute(false)]
[assembly: CLSCompliantAttribute(false)]
[assembly: AssemblyCompanyAttribute("Jury Soldatenkov")]
[assembly: AssemblyVersionAttribute("1.0.0.8")]
[assembly: AssemblyFileVersionAttribute("1.0.0.8")]
[assembly: AssemblyInformationalVersionAttribute("1.0.0.946cc18ec8f12e28f60da644a8845b1abc1c62bb")]
[assembly: AssemblyTitleAttribute("Solyutor.EventPublisher")]
[assembly: AssemblyProductAttribute("Solyutor.EventPublisher")]
[assembly: AssemblyDescriptionAttribute("Solyutor.EventPublisher is a product of Jury Soldatenkov - ..")]
[assembly: AssemblyTrademarkAttribute("Solyutor.EventPublisher - Jury Soldatenkov")]
[assembly: AssemblyCopyrightAttribute("Copyright ©  2011 Jury Soldatenkov, - Original author or authors")]

